# Do you need support or have an idea for improvement? dsc.gg/hesodev

# Time between messages in seconds
timeDelay: 280

# Randomize messages?
random: false

# Sound effect on message send - use names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'

# Message List
# Supports colors using &
Messages:
  - '&eFirst message, change in config.yml'
  - '&cSecond message, change in config.yml'
  - '&bThird message, change in config.yml'

# Allow Raw Messages? (List below)
# If you use RAW Messages, standard will be deactivated
allowRaw: false

# Row Messages - use for hover messages, etc..
# How to use raw messages? https://www.digminecraft.com/game_commands/tellraw_command.php
RawMessages:
  - '{"text":"Hover message!","color":"red","bold":false,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"I am a hover message!","color":"orange","bold":true}]}}}'
  - '{"text":"Click for command!","color":"white","bold":false,"clickEvent":{"action":"run_command","value":"/say COMMAND WORKS"}}'


#DO NOT EDIT THIS
configVersion: '4.0'