# Do you need support or have an idea for improvement? dsc.gg/hesodev

# Time between messages in seconds
timeDelay: 280

# Randomize messages?
random: false

# Settings for pitch (Default 1.0)
pitch: 1.0f

# Settings for sound volume (Default 1.0)
volume: 1.0f

# Sound effect on message send - use names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sound: 'ENTITY_EXPERIENCE_ORB_PICKUP'

# Message List
# Supports colors using &
# Also supports Gradient!
Messages:
  - '&eFirst message, change in config.yml'
  - '{#b36000>}Second message{#72cc00<} &3Some gradient'
  - '&cThird message, change in config.yml'
  - '{#b36000}Fourth message, change in config.yml'
  - '{#DC143C>}* | Announcement{#FF0000<} {#FFFFFF}&l>> &eNeed help with a plugin?! {#FF7F50>}dsc.gg/hesodev{#FF8C00<}'

# Allow Raw Messages? (List below)
# If you use RAW Messages, standard will be deactivated
allowRaw: false

# Row Messages - use for hover messages, etc..
# How to use raw messages? https://www.digminecraft.com/game_commands/tellraw_command.php
# or use this generator https://minecraft.tools/en/tellraw.php

# More support on dsc.gg/hesodev
RawMessages:
  - '{"text":"Hover message!","color":"red","bold":false,"hoverEvent":{"action":"show_text","value":{"text":"","extra":[{"text":"I am a hover message!","color":"orange","bold":true}]}}}'
  - '{"text":"Click for command!","color":"white","bold":false,"clickEvent":{"action":"run_command","value":"/say COMMAND WORKS"}}'
