# Do you need support or have an idea for improvement? dsc.gg/hesodev

# Time between messages in seconds
timeDelay: 280
# Randomize messages?
random: false
# Sound effect on message send - use names from https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html
sound: "ENTITY_EXPERIENCE_ORB_PICKUP"
# Message List
# Supports colors using &
Messages:
  - "&eFirst message, change in config.yml"
  - "&cSecond message, change in config.yml"
  - "&bThird message, change in config.yml"