name: AutoMessages
version: '${version}'
main: cz.hesovodoupe.automessages.AutoMessages
api-version: '1.16'
authors: [Heso]
description: AutoMessages
website: snezik.cz

commands:
  automessage:
    description: Reload server
    usage: /<command>
    permission: am.reload
    permission-message: ""

permissions:
  am.reload:
    description: "Permissions for reload"
    default: false
